import { isExportable } from "../shared/kinds.ts";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { PLACEHOLDER, POSIX_NAME, placeholdersIn, type Entry, type Param } from "../shared/schema.ts";
import { GENERATED, LOADER, TAG } from "./paths.ts";

const exec = promisify(execFile);

/** First line of every file Ramz generates: how we recognise our own output. */
export const HEADER = "# Generated by Ramz. Edits are overwritten - manage entries in the Ramz app.";

/** Wrap for single-quoted shell context: close, escape, reopen. */
function sq(s: string) {
  return `'${s.replaceAll("'", `'\\''`)}'`;
}

/** Escape for use inside a double-quoted ${n:-...} expansion. */
function dq(s: string) {
  return s.replace(/([\\"`$])/g, "\\$1");
}

/**
 * How a placeholder is substituted depends on the quoting around it in the template:
 * bare text needs its own quotes, inside double quotes it must not add any, and inside
 * single quotes it has to break out or the shell would treat it as literal text.
 */
type Quote = "none" | "double" | "single";

function positional(index: number, p: Param, quote: Quote) {
  const n = index + 1;
  const inner = p.default ? `\${${n}:-${dq(p.default)}}` : `$${n}`;
  if (quote === "double") return inner;
  if (quote === "single") return `'"${inner}"'`;
  return `"${inner}"`;
}

/** Quote context at every index of `s`, tracking backslash escapes. */
function quoteMap(s: string): Quote[] {
  const out: Quote[] = [];
  let state: Quote = "none";
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (state === "double" && c === "\\") { out.push(state); out.push(state); i++; continue; }
    if (c === '"' && state !== "single") state = state === "double" ? "none" : "double";
    else if (c === "'" && state !== "double") state = state === "single" ? "none" : "single";
    out.push(state);
  }
  return out;
}

export type ExportWarning = { entryId?: string; name?: string; level: "error" | "warn"; message: string };

/** An alias cannot take arguments, and a multi-line alias is a worse fit than a function. */
export function isFunction(e: Entry): boolean {
  return e.params.length > 0 || e.asFunction || e.command.trim().includes("\n");
}

export function renderEntry(e: Entry): string {
  const header = e.description.trim() ? `# ${e.description.trim().split("\n")[0]}\n` : "";
  const body = e.command.trim();

  if (!isFunction(e)) {
    return `${header}alias ${e.name}=${sq(body)}`;
  }

  const index = new Map(e.params.map((p, i) => [p.name, i] as const));
  const quotes = quoteMap(body);
  const fnBody = body.replace(PLACEHOLDER, (m, key: string, at: number) => {
    const i = index.get(key);
    if (i === undefined) return m;
    return positional(i, e.params[i], quotes[at] ?? "none");
  });
  const argDocs = e.params
    .map((p, i) => `#   $${i + 1} ${p.name}${p.required ? "" : " (optional)"}${p.description ? ` - ${p.description}` : ""}`)
    .join("\n");
  const indented = fnBody
    .split("\n")
    .map((l) => `  ${l}`)
    .join("\n");
  return `${header}${argDocs}\n${e.name}() {\n${indented}\n}`;
}

export function validateForExport(entries: Entry[]): ExportWarning[] {
  const out: ExportWarning[] = [];
  const byName = new Map<string, Entry[]>();

  for (const e of entries) {
    byName.set(e.name, [...(byName.get(e.name) ?? []), e]);

    if (isFunction(e) && !POSIX_NAME.test(e.name)) {
      out.push({
        entryId: e.id,
        name: e.name,
        level: "warn",
        message: "exports as a function with a hyphen or dot in the name: fine in bash and zsh, not in /bin/sh",
      });
    }

    const declared = new Set(e.params.map((p) => p.name));
    for (const ph of placeholdersIn(e.command)) {
      if (!declared.has(ph)) {
        out.push({
          entryId: e.id,
          name: e.name,
          level: "error",
          message: `uses {{${ph}}} but no such argument is defined`,
        });
      }
    }
    const firstOptional = e.params.findIndex((p) => p.default);
    const lastRequired = e.params.map((p) => !p.default).lastIndexOf(true);
    if (firstOptional !== -1 && lastRequired > firstOptional) {
      out.push({
        entryId: e.id,
        name: e.name,
        level: "warn",
        message: `"${e.params[firstOptional].name}" has a default but comes before "${e.params[lastRequired].name}", which does not, so callers have to pass an empty string to skip it`,
      });
    }

    for (const p of e.params) {
      if (!e.command.includes(`{{${p.name}}}`)) {
        out.push({
          entryId: e.id,
          name: e.name,
          level: "warn",
          message: `argument "${p.name}" is never used in the command`,
        });
      }
    }
  }

  for (const [name, list] of byName) {
    if (list.length > 1) {
      out.push({ name, level: "error", message: `${list.length} entries share the name "${name}"` });
    }
  }
  return out;
}

/** Names that already resolve to something on $PATH (or a builtin). */
export async function shadowCheck(names: string[]): Promise<Record<string, string>> {
  if (names.length === 0) return {};
  const script = names.map((n) => `printf '%s\\t' ${sq(n)}; command -v ${sq(n)} 2>/dev/null || echo`).join("\n");
  try {
    const { stdout } = await exec("/bin/sh", ["-c", script], { timeout: 5000 });
    const hits: Record<string, string> = {};
    for (const line of stdout.split("\n")) {
      const [name, resolved] = line.split("\t");
      if (name && resolved?.trim()) hits[name] = resolved.trim();
    }
    return hits;
  } catch {
    return {};
  }
}

export function renderAliases(entries: Entry[]): string {
  const exportable = entries.filter(isExportable);
  const byName = (a: Entry, b: Entry) => a.name.localeCompare(b.name);
  // Aliases first: a function body only picks up an alias it calls if that alias
  // is already defined when the function is parsed.
  const aliases = exportable.filter((e) => !isFunction(e)).sort(byName);
  const functions = exportable.filter(isFunction).sort(byName);
  const sections = [
    aliases.length ? aliases.map(renderEntry).join("\n\n") : "",
    functions.length ? functions.map(renderEntry).join("\n\n") : "",
  ].filter(Boolean);
  const body = sections.length ? sections.join("\n\n") : "# Nothing exported yet.";
  return `${HEADER}\n# ${new Date().toISOString()}\n\n${body}\n`;
}

/**
 * The loader. Finds its own directory instead of having one baked in, so the
 * directory can be moved and nothing else needs to change. Works in sh, bash
 * and zsh, and leaves no variables behind.
 */
export function renderLoader(files: string[] = GENERATED): string {
  return [
    HEADER,
    "# Sourced by one line in your shell rc. Delete this directory to remove Ramz entirely.",
    'if [ -n "${BASH_SOURCE-}" ]; then _ramz_self=$BASH_SOURCE',
    `elif [ -n "\${ZSH_VERSION-}" ]; then eval '_ramz_self=\${(%):-%x}'`,
    "else _ramz_self=$0; fi",
    '_ramz_dir=$(CDPATH= cd -- "$(dirname -- "$_ramz_self")" 2>/dev/null && pwd)',
    `for _ramz_f in ${files.join(" ")}; do`,
    '  [ -r "$_ramz_dir/$_ramz_f" ] && . "$_ramz_dir/$_ramz_f"',
    "done",
    "unset _ramz_self _ramz_dir _ramz_f",
    "",
  ].join("\n");
}

/** Our line in an rc file: the tagged one we wrote, or any line sourcing the loader. */
function isSourceLine(line: string) {
  const t = line.trim();
  if (!t || t.startsWith("#")) return false;
  return t.includes(LOADER) && (t.endsWith(TAG) || /(^|\s)(\.|source)\s/.test(t));
}

export function findSourceLines(text: string): number[] {
  return text.split("\n").flatMap((l, i) => (isSourceLine(l) ? [i] : []));
}

/** Append the line once; a file that already has it comes back untouched. */
export function withSourceLine(text: string, line: string): string {
  if (findSourceLines(text).length > 0) return text;
  const sep = text.length === 0 || text.endsWith("\n") ? "" : "\n";
  return `${text}${sep}${text.length ? "\n" : ""}${line}\n`;
}

/** Drop our line (or lines), plus the blank line we padded it with. */
export function withoutSourceLine(text: string): string {
  const lines = text.split("\n");
  const drop = new Set(findSourceLines(text));
  for (const i of [...drop]) {
    const nextIsGone = i + 1 >= lines.length || lines[i + 1].trim() === "";
    if (i > 0 && lines[i - 1].trim() === "" && nextIsGone) drop.add(i - 1);
  }
  return lines.filter((_, i) => !drop.has(i)).join("\n");
}

export type ParsedAlias = {
  name: string;
  command: string;
  params: { name: string; default: string; required: boolean }[];
  form: "alias" | "function";
  /** The comment block sitting directly above the definition, if any. */
  title: string;
  description: string;
};

/** A line that defines something we deliberately do not model. */
export type SkippedLine = { line: string; reason: string };

function unquote(raw: string): string {
  const s = raw.trim();
  if (s.startsWith("'") && s.endsWith("'") && s.length > 1) {
    return s.slice(1, -1).replaceAll(`'\\''`, "'");
  }
  if (s.startsWith('"') && s.endsWith('"') && s.length > 1) {
    return s.slice(1, -1).replace(/\\(["\\`$])/g, "$1");
  }
  return s;
}

/** Turn $1 / ${1:-x} into {{arg1}} placeholders and collect the implied params. */
function positionalsToPlaceholders(body: string) {
  const params = new Map<number, { name: string; default: string; required: boolean }>();
  const command = body.replace(/"?\$\{(\d)(?::-([^}]*))?\}"?|"?\$(\d)"?/g, (m, braced, def, bare) => {
    const n = Number(braced ?? bare);
    if (!n) return m;
    const name = `arg${n}`;
    if (!params.has(n)) params.set(n, { name, default: def ?? "", required: def === undefined });
    return `{{${name}}}`;
  });
  return { command, params: [...params.entries()].sort(([a], [b]) => a - b).map(([, p]) => p) };
}

/** Comment lines directly above `i`, nearest last, stopping at a blank line. */
function commentAbove(lines: string[], i: number): string[] {
  const out: string[] = [];
  for (let j = i - 1; j >= 0; j--) {
    const t = lines[j].trim();
    if (!t.startsWith("#")) break;
    const text = t.replace(/^#+\s?/, "").trim();
    if (!text) break;
    out.unshift(text);
  }
  return out;
}

function labels(lines: string[], i: number, name: string) {
  const comment = commentAbove(lines, i);
  // A lone word above a definition reads as a section header, not a title.
  const usable = comment[0] && comment[0].split(/\s+/).length > 1 ? comment : comment.slice(1);
  return { title: usable[0] ?? name, description: usable.slice(1).join(" ") };
}

/** Best-effort parse of aliases and simple functions out of a shell file. */
export function parseShellFile(text: string): { found: ParsedAlias[]; skipped: SkippedLine[] } {
  const lines = text.split("\n");
  const out: ParsedAlias[] = [];
  const skipped: SkippedLine[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    if (/^export\s+[A-Za-z_]/.test(trimmed)) {
      skipped.push({ line: trimmed, reason: "environment variable, not a command" });
      continue;
    }
    if (/^(\.|source)\s/.test(trimmed)) {
      skipped.push({ line: trimmed, reason: "sources another file" });
      continue;
    }

    const aliasMatch = trimmed.match(/^alias\s+([A-Za-z_][A-Za-z0-9_.-]*)=(.*)$/);
    if (aliasMatch) {
      out.push({
        name: aliasMatch[1],
        command: unquote(aliasMatch[2]),
        params: [],
        form: "alias",
        ...labels(lines, i, aliasMatch[1]),
      });
      continue;
    }

    const fnMatch = trimmed.match(/^(?:function\s+)?([A-Za-z_][A-Za-z0-9_.-]*)\s*(?:\(\s*\))?\s*\{(.*)$/);
    if (fnMatch) {
      const start = i;
      let depth = 1;
      const collected: string[] = [];
      let rest = fnMatch[2];
      let j = i;
      while (j < lines.length) {
        for (const ch of rest) {
          if (ch === "{") depth++;
          else if (ch === "}") depth--;
        }
        if (depth <= 0) {
          collected.push(rest.replace(/\}\s*$/, ""));
          break;
        }
        collected.push(rest);
        j++;
        rest = lines[j] ?? "";
      }
      i = j;
      const body = collected.join("\n").split("\n").map((l) => l.trim()).filter(Boolean).join("\n").replace(/;$/, "");
      if (!body) continue;
      const { command, params } = positionalsToPlaceholders(body);
      out.push({ name: fnMatch[1], command, params, form: "function", ...labels(lines, start, fnMatch[1]) });
    }
  }
  return { found: out, skipped };
}
